# Generated by Django 2.2.1 on 2019-05-29 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190429_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='is_manager',
            new_name='is_doctor',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='is_operative',
            new_name='is_labTech',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='is_supervisor',
            new_name='is_receptionist',
        ),
    ]
