# Generated by Django 2.2.1 on 2019-06-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_role_is_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='role',
            name='is_doctor',
        ),
        migrations.RemoveField(
            model_name='role',
            name='is_labTech',
        ),
        migrations.RemoveField(
            model_name='role',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='role',
            name='is_receptionist',
        ),
        migrations.AddField(
            model_name='role',
            name='role',
            field=models.CharField(default='new_user', max_length=20),
        ),
    ]
