# Generated by Django 2.2.1 on 2019-06-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190617_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='status',
            field=models.CharField(default='active', max_length=10),
        ),
    ]
