# Generated by Django 2.2.1 on 2019-06-23 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0007_delete_teststatus'),
        ('Laboratory', '0004_results_tests'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=300)),
                ('status', models.CharField(default='Not Done', max_length=10)),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reception.Lab')),
            ],
        ),
    ]
