# Generated by Django 2.2.1 on 2019-06-26 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakenDrugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=200)),
                ('status', models.CharField(default='Not Paid', max_length=10)),
                ('quantity', models.IntegerField()),
                ('totalPrice', models.IntegerField()),
                ('drugName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.Drugs')),
            ],
        ),
    ]
