# Generated by Django 2.2.1 on 2019-06-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_takendrugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takendrugs',
            name='drugName',
            field=models.CharField(max_length=200),
        ),
    ]
