# Generated by Django 2.2.1 on 2019-07-03 08:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_auto_20190627_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='takendrugs',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
