# Generated by Django 2.2.1 on 2019-07-03 11:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_takendrugs_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takendrugs',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
