# Generated by Django 2.2.1 on 2019-08-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_drugssupplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='expire_date',
            field=models.DateTimeField(),
        ),
    ]
