# Generated by Django 2.2.1 on 2019-08-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0011_auto_20190805_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='expire_date',
            field=models.DateTimeField(verbose_name='%B %d %Y'),
        ),
    ]
