# Generated by Django 2.2.1 on 2019-08-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0012_auto_20190816_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='expire_date',
            field=models.DateTimeField(),
        ),
    ]
