# Generated by Django 2.2.1 on 2019-08-19 06:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0013_auto_20190816_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takendrugs',
            name='status',
        ),
        migrations.AddField(
            model_name='drugs',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='drugssupplier',
            name='phone',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
