# Generated by Django 2.2.1 on 2019-06-13 12:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=300)),
                ('doctor', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=300)),
                ('tests', models.TextField()),
                ('totalPrice', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='address2',
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.TextField(default='kampala'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='code',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='dob',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='image',
            field=models.ImageField(default='default.jpeg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_history',
            field=models.TextField(default='N?A'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='occupation',
            field=models.CharField(default='Student', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='payment',
            field=models.CharField(default='cash', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(default='paid', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='test_data',
            field=models.CharField(default=1, max_length=128, verbose_name='Test Data'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CashLabStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=300)),
                ('paid', models.BooleanField(default=False)),
                ('unpaid', models.BooleanField(default=True)),
                ('labTest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reception.Lab')),
            ],
        ),
        migrations.CreateModel(
            name='CashAppointmentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=300)),
                ('paid', models.BooleanField(default=False)),
                ('unpaid', models.BooleanField(default=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reception.Appointment')),
            ],
        ),
    ]
