# Generated by Django 2.2.1 on 2019-06-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0002_auto_20190613_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='Instructions',
            field=models.CharField(default='N/A', max_length=300),
            preserve_default=False,
        ),
    ]
