# Generated by Django 2.2.1 on 2019-06-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0003_lab_instructions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashappointmentstatus',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='cashappointmentstatus',
            name='unpaid',
        ),
        migrations.RemoveField(
            model_name='cashlabstatus',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='cashlabstatus',
            name='unpaid',
        ),
        migrations.AddField(
            model_name='cashappointmentstatus',
            name='status',
            field=models.CharField(default='Unpaid', max_length=10),
        ),
        migrations.AddField(
            model_name='cashlabstatus',
            name='status',
            field=models.CharField(default='Unpaid', max_length=10),
        ),
    ]
