# Generated by Django 2.2.1 on 2019-06-17 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0004_auto_20190617_0739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'get_latest_by': 'created_date'},
        ),
    ]
