# Generated by Django 2.2.1 on 2019-06-20 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0005_auto_20190617_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='Instructions',
        ),
        migrations.AddField(
            model_name='lab',
            name='status',
            field=models.CharField(default='Not done', max_length=10),
        ),
        migrations.CreateModel(
            name='TestStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=300)),
                ('status', models.CharField(default='Not Done', max_length=10)),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reception.Lab')),
            ],
        ),
    ]
