# Generated by Django 2.2.1 on 2019-06-23 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0006_auto_20190620_1322'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestStatus',
        ),
    ]
