# Generated by Django 2.2.1 on 2019-07-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0008_appointment_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='medical_history',
        ),
        migrations.AddField(
            model_name='patient',
            name='life_status',
            field=models.CharField(default='alive', max_length=100),
        ),
    ]
