# Generated by Django 2.2.1 on 2019-07-22 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0009_auto_20190722_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='life_status',
        ),
    ]
