# Generated by Django 2.2.1 on 2019-07-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0010_remove_patient_life_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
