# Generated by Django 2.2.1 on 2019-10-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0012_auto_20191002_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.ImageField(upload_to='profile_pics'),
        ),
    ]
