# Generated by Django 2.2.1 on 2019-10-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0014_auto_20191003_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
