# Generated by Django 2.2.1 on 2019-10-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0015_auto_20191003_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='department',
            field=models.CharField(default='gynecologyst', max_length=200),
            preserve_default=False,
        ),
    ]
