# Generated by Django 2.2.1 on 2019-10-09 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0017_auto_20191009_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashappointmentstatus',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cashlabstatus',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
