# Generated by Django 2.2.1 on 2019-10-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0018_auto_20191009_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashappointmentstatus',
            name='payment_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashlabstatus',
            name='payment_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
