# Generated by Django 2.2.1 on 2019-07-18 08:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reception', '0008_appointment_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='OutPatient', max_length=10)),
                ('prescription', models.TextField()),
                ('report', models.TextField()),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reception.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_prescription', models.TextField()),
                ('nurse_report', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reception.Patient')),
            ],
        ),
    ]
