# Generated by Django 2.2.1 on 2019-06-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=200)),
                ('symptoms', models.CharField(max_length=200)),
                ('prescription', models.CharField(max_length=200)),
            ],
        ),
    ]
