# Generated by Django 2.2.1 on 2019-06-11 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_reports'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reports',
            old_name='prescription',
            new_name='report',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='symptoms',
        ),
    ]
