# Generated by Django 2.2.1 on 2019-06-17 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_reports_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reports',
            options={'get_latest_by': 'created_date'},
        ),
    ]
