# Generated by Django 2.2.1 on 2019-07-03 11:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_instructionsforpharmacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionsForNurse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=200)),
                ('instructions', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'get_latest_by': 'created_date',
            },
        ),
    ]
