# Generated by Django 2.2.1 on 2019-10-14 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0051_auto_20191014_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allotment',
            name='number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctor.Room'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor'),
        ),
    ]
