# Generated by Django 2.2.1 on 2019-10-14 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0059_auto_20191014_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allotment',
            name='number',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='prices',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor'),
        ),
    ]
