# Generated by Django 2.2.1 on 2019-10-14 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0062_auto_20191014_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='allotment',
            name='patient',
            field=models.CharField(default='cheke23sa', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prices',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor'),
        ),
    ]
