# Generated by Django 2.2.1 on 2019-10-16 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0063_auto_20191014_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='diagnosis',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prices',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='patient',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reports',
            name='report',
            field=models.CharField(max_length=300),
        ),
    ]
