# Generated by Django 2.2.1 on 2019-11-13 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0066_auto_20191113_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptoms',
            name='appointment',
        ),
        migrations.AlterField(
            model_name='prices',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor'),
        ),
    ]
