# Generated by Django 2.2.1 on 2019-07-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='corpses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=300)),
                ('date_of_death', models.CharField(max_length=300)),
                ('death_report', models.TextField()),
            ],
        ),
    ]
