# Generated by Django 2.2.1 on 2019-07-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortury', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpses',
            name='patient_code',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='corpses',
            name='death_report',
            field=models.CharField(max_length=500),
        ),
    ]
