# Generated by Django 2.2.1 on 2019-07-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortury', '0004_auto_20190723_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='morturyPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='corpses',
            name='release_status',
        ),
    ]
