# Generated by Django 2.2.1 on 2019-07-23 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mortury', '0006_auto_20190723_0834'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='morturyPayment',
            new_name='Mpayment',
        ),
    ]
