# Generated by Django 2.2.1 on 2019-07-08 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0011_instructionsfornurse'),
    ]

    operations = [
        migrations.CreateModel(
            name='icuFindings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=200)),
                ('findings', models.CharField(max_length=200)),
                ('Status', models.CharField(max_length=100)),
                ('Instructions', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctor.InstructionsForNurse')),
            ],
        ),
    ]
