# Generated by Django 2.2.1 on 2019-07-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icufindings',
            name='Status',
            field=models.CharField(default='Not Done', max_length=10),
        ),
    ]
